default: &default
  adapter: sqlserver
  encoding: utf8
  reconnect: false
  host: <%= SearchBot::SECRETS.database.host %>
  port: 1433
  username: <%= SearchBot::SECRETS.database.user %>
  password: <%= SearchBot::SECRETS.database.password %>
  timeout: 25

encore:
  <<: *default
  database: Encore

main:
  <<: *default
  database: GoogleBot