default: &default
  encoding: utf8
  reconnect: false
  timeout: 25

encore:
  <<: *default
  adapter: sqlserver
  database: Encore
  host: <%= SearchBot::SECRETS.encore_database.host %>
  port: 1433
  username: <%= SearchBot::SECRETS.encore_database.user %>
  password: <%= SearchBot::SECRETS.encore_database.password %>

main:
  <<: *default
  adapter: postgresql
  database: SearchBot
  host: <%= SearchBot::SECRETS.postgres_database.host %>
  port: 5432
  username: <%= SearchBot::SECRETS.postgres_database.user %>
  password: <%= SearchBot::SECRETS.postgres_database.password %>